### Register
POST http://localhost:3005/api/auth/reg
Content-Type: application/json

{
    "email":"webdevsetup239@gmail.com",
    "password":"Admin@123",
    "first_name":"dhanraj"
}
 
###  Login
POST http://localhost:3005/api/auth/login
Content-Type: application/json

{
    "email":"webdevsetup239@gmail.com",
    "password":"Admin@123"
}
###  Login Admin
POST http://localhost:3005/api/auth/login
Content-Type: application/json

{
    "email":"choudharydhanraj239@gmail.com",
    "password":"Admin$123%4654"
}

### forget password
POST http://localhost:3005/api/auth/forget-password
Content-Type: application/json

{
    "email":"webdevsetup239@gmail.com"
}

### verify otp and password password
PUT http://localhost:3005/api/auth/verify-otp-update
Content-Type: application/json

{
    "email":"webdevsetup239@gmail.com",
    "password":"Admin$123",
    "otp":"412715"
}