### find course by id
GET  http://localhost:3005/api/course/1

### find course by id
GET  http://localhost:3005/api/course/all

### find courses by filters
GET  http://localhost:3005/api/course/filters
Content-Type: application/json

{
   "name":"dj",
   "tag":[],
   "category":[]
}

###  create course
POST   http://localhost:3005/api/course/create
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ3ZWJkZXZzZXR1cDIzOUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRoYUYubm1wWE5OZ1dkc1NSaXFOVFllUC5WUkNDb3JNdm1LWEtkd21jc0VjYTcxdjhyNjJZQyIsInByb2ZpbGVfaW1nX3VybCI6Imh0dHBzOi8vY2RuLnBpeGFiYXkuY29tL3Bob3RvLzIwMTUvMTAvMDUvMjIvMzcvYmxhbmstcHJvZmlsZS1waWN0dXJlLTk3MzQ2MF85NjBfNzIwLnBuZyIsImZpcnN0X25hbWUiOiJkaGFucmFqIiwibGFzdF9uYW1lIjpudWxsLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzEyNTc4OTQyLCJleHAiOjE3MTI1ODI1NDJ9.mZkg0QEcyO66ufCoDMptLLOhDl_KB0UWY9NtI2uDlyA
Content-Type: application/json

{
    "name":"dj",
   "tag":["c","java"],
   "category":["coding","data structure"],
   "duration":"10hour",
   "language":"english"
}
