### find course by id
GET  http://localhost:3005/api/enrollment/enrolled
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ3ZWJkZXZzZXR1cDIzOUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRoYUYubm1wWE5OZ1dkc1NSaXFOVFllUC5WUkNDb3JNdm1LWEtkd21jc0VjYTcxdjhyNjJZQyIsInByb2ZpbGVfaW1nX3VybCI6Imh0dHBzOi8vY2RuLnBpeGFiYXkuY29tL3Bob3RvLzIwMTUvMTAvMDUvMjIvMzcvYmxhbmstcHJvZmlsZS1waWN0dXJlLTk3MzQ2MF85NjBfNzIwLnBuZyIsImZpcnN0X25hbWUiOiJkaGFucmFqIiwibGFzdF9uYW1lIjpudWxsLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzEyNjU4Nzc1LCJleHAiOjE3MTI2NjIzNzV9.Nk1_gHK6bYe8PGNsk7x2XmCkWfJZ0MNQTqX2-KGt2dA



### Enrolled in course
POST  http://localhost:3005/api/enrollment/create/1
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ3ZWJkZXZzZXR1cDIzOUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRoYUYubm1wWE5OZ1dkc1NSaXFOVFllUC5WUkNDb3JNdm1LWEtkd21jc0VjYTcxdjhyNjJZQyIsInByb2ZpbGVfaW1nX3VybCI6Imh0dHBzOi8vY2RuLnBpeGFiYXkuY29tL3Bob3RvLzIwMTUvMTAvMDUvMjIvMzcvYmxhbmstcHJvZmlsZS1waWN0dXJlLTk3MzQ2MF85NjBfNzIwLnBuZyIsImZpcnN0X25hbWUiOiJkaGFucmFqIiwibGFzdF9uYW1lIjpudWxsLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzEyNjU4Nzc1LCJleHAiOjE3MTI2NjIzNzV9.Nk1_gHK6bYe8PGNsk7x2XmCkWfJZ0MNQTqX2-KGt2dA


### unenrolled this course
DELETE   http://localhost:3005/api/enrollment/unenrolled/7
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ3ZWJkZXZzZXR1cDIzOUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRoYUYubm1wWE5OZ1dkc1NSaXFOVFllUC5WUkNDb3JNdm1LWEtkd21jc0VjYTcxdjhyNjJZQyIsInByb2ZpbGVfaW1nX3VybCI6Imh0dHBzOi8vY2RuLnBpeGFiYXkuY29tL3Bob3RvLzIwMTUvMTAvMDUvMjIvMzcvYmxhbmstcHJvZmlsZS1waWN0dXJlLTk3MzQ2MF85NjBfNzIwLnBuZyIsImZpcnN0X25hbWUiOiJkaGFucmFqIiwibGFzdF9uYW1lIjpudWxsLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzEyNjU4Nzc1LCJleHAiOjE3MTI2NjIzNzV9.Nk1_gHK6bYe8PGNsk7x2XmCkWfJZ0MNQTqX2-KGt2dA



