### find course by id
GET  http://localhost:3005/api/enrollment/enrolled
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjaG91ZGhhcnlkaGFucmFqMjM5QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDloN3hFWXdOVTJXeEhNUkVDdEc3SGUyUmY3WE00bXliU3ZzOE14c1dEd2doeXZIVjBEOG9pIiwicHJvZmlsZV9pbWdfdXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAxNS8xMC8wNS8yMi8zNy9ibGFuay1wcm9maWxlLXBpY3R1cmUtOTczNDYwXzk2MF83MjAucG5nIiwiZmlyc3RfbmFtZSI6ImRoYW5yYWoiLCJsYXN0X25hbWUiOm51bGwsInJvbGUiOlsidXNlciJdLCJpYXQiOjE3MTI1NzEyNjEsImV4cCI6MTcxMjU3NDg2MX0.2k4cO7F2pf2APvIUOx92stkUClCsihMNb-bzdP0CJPg



### Enrolled in course
POST  http://localhost:3005/api/enrollment/create/1
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaG91ZGhhcnlkaGFucmFqMjM5QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHVHaXhpeWl0OHNVcFA1amJxTk0vVC5UMzh5SnJhRDRIcVJoLnhLMjVVbk4ubjdLSFNPcXVDIiwicHJvZmlsZV9pbWdfdXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAxNS8xMC8wNS8yMi8zNy9ibGFuay1wcm9maWxlLXBpY3R1cmUtOTczNDYwXzk2MF83MjAucG5nIiwiZmlyc3RfbmFtZSI6InN1cGVyIiwibGFzdF9uYW1lIjoiYWRtaW4iLCJyb2xlIjpbInVzZXIiLCJzdXBlckFkbWluIl0sImlhdCI6MTcxMjU3NzY2MiwiZXhwIjoxNzEyNTgxMjYyfQ.gggIh3nip2WbUVAfle9uLfyxUatIEuSwMvsc2-4JFzc


### unenrolled this course
DELETE   http://localhost:3005/api/enrollment/unenrolled/5
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjaG91ZGhhcnlkaGFucmFqMjM5QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDloN3hFWXdOVTJXeEhNUkVDdEc3SGUyUmY3WE00bXliU3ZzOE14c1dEd2doeXZIVjBEOG9pIiwicHJvZmlsZV9pbWdfdXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAxNS8xMC8wNS8yMi8zNy9ibGFuay1wcm9maWxlLXBpY3R1cmUtOTczNDYwXzk2MF83MjAucG5nIiwiZmlyc3RfbmFtZSI6ImRoYW5yYWoiLCJsYXN0X25hbWUiOm51bGwsInJvbGUiOlsidXNlciJdLCJpYXQiOjE3MTI1NzEyNjEsImV4cCI6MTcxMjU3NDg2MX0.2k4cO7F2pf2APvIUOx92stkUClCsihMNb-bzdP0CJPg



