### reset password
POST  http://localhost:3005/api/user/reset-password
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ3ZWJkZXZzZXR1cDIzOUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRoYUYubm1wWE5OZ1dkc1NSaXFOVFllUC5WUkNDb3JNdm1LWEtkd21jc0VjYTcxdjhyNjJZQyIsInByb2ZpbGVfaW1nX3VybCI6Imh0dHBzOi8vY2RuLnBpeGFiYXkuY29tL3Bob3RvLzIwMTUvMTAvMDUvMjIvMzcvYmxhbmstcHJvZmlsZS1waWN0dXJlLTk3MzQ2MF85NjBfNzIwLnBuZyIsImZpcnN0X25hbWUiOiJkaGFucmFqIiwibGFzdF9uYW1lIjpudWxsLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzEyNjYyNDU1LCJleHAiOjE3MTI2NjYwNTV9.NixSZPRPlKUK6OxvG-Bdba94c3GujRWYtiPq-zkaWhk

### otp and update password
PUT  http://localhost:3005/api/user/verify-otp-update-password
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ3ZWJkZXZzZXR1cDIzOUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRoYUYubm1wWE5OZ1dkc1NSaXFOVFllUC5WUkNDb3JNdm1LWEtkd21jc0VjYTcxdjhyNjJZQyIsInByb2ZpbGVfaW1nX3VybCI6Imh0dHBzOi8vY2RuLnBpeGFiYXkuY29tL3Bob3RvLzIwMTUvMTAvMDUvMjIvMzcvYmxhbmstcHJvZmlsZS1waWN0dXJlLTk3MzQ2MF85NjBfNzIwLnBuZyIsImZpcnN0X25hbWUiOiJkaGFucmFqIiwibGFzdF9uYW1lIjpudWxsLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzEyNjYyNDU1LCJleHAiOjE3MTI2NjYwNTV9.NixSZPRPlKUK6OxvG-Bdba94c3GujRWYtiPq-zkaWhk
Content-Type: application/json

{
    "otp":"656211",
    "password":"Admin@123"
}